spring:
  application:
    name: ElectronicStore
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:29092
  datasource:
    url: jdbc:mysql://localhost:3307/electronicstore_kc?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/electronicstore}

keycloak:
  realm: electronicstore
  client-id: electronicstore-app
